project:
  type: book
  output-dir: docs

execute:
  freeze: auto

book:
  title: "A Little R Survival Kit"
  author: "Eric S. Ho, Ph.D."
  date: "6/16/2026"
  chapters:
    - index.qmd
    - 01_Part1_Basic_R.qmd
    - 02_Data_Wrangling.qmd
    - 03-Data-Visualization.qmd
    - 04_Dive_Deeper.qmd

bibliography:
  - book.bib
  - packages.bib
  
format:
  html:
    theme: cosmo
    css: style.css
    code-copy: true
    linkcolor: "#096B72"
  pdf:
    documentclass: scrreprt
    pdf-engine: xelatex
    include-in-header: preamble.tex
    keep-tex: true
    cite-method: natbib
  epub: default

