{
  "hash": "d2df1780e0e341bb5a0e474b9dbfc6fa",
  "result": {
    "engine": "knitr",
    "markdown": "# Part I {.unnumbered}\n\nPart I focuses on the basic R objects and commands, such as atomic and object variables, descriptive statistical functions, and data wrangling using base R and `tidyverse`.\n\n# Basic R\n\n## Learning Objectives: {-}\n\nThis chapter covers common basic R functions used for statistical analysis. After finishing this chapter, you should be able to:\n\n-   Define R variables.\n\n-   Know the differences between an atomic variable and an object variable.\n\n-   Perform arithmetic operators.\n\n-   Store results in variables.\n\n-   Format and print the contents of variables to the console.\n\n-   Calculate non-robust and robust statistics.\n\n-   Use `seq()` and `with()` functions.\n\nAs R scripting is a hands-on topic, I encourage you to open RStudio alongside this book and try out the code to maximize understanding. Let's get started.\n\n## Rules of Naming Variables\n\nThe name of an R variable must follow these two rules:\n\n1.  It must begin with a letter (A-Z or a-z), a dot \"`.`\", or an underscore \"`_`\", and\n\n2.  Subsequent characters can be any combinations of letters, digits (0-9), \"`.`\", or \"`_`\".\n\nNote that:\n\n-   Variable names are case-sensitive, e.g., `volume` and `Volume` are different in the eyes of R.\n\n-   Give meaningful names to variables, e.g., `zone2` instead of `z` or even worse `x`. That will help a bunch in understanding the code, even your own code.\n\n-   Watch out that some names have been used by R, e.g., `c`, and `head` are function names. However, R is permissive for people to use them as variable names. So, the rule of thumb is to exercise self-discipline not to choose R function names as variable names.\n\n## R Objects\n\n### Atomic and Object Variables {#atomic-and-object-variables}\n\nR classifies variables into two broad categories: **atomic type** , and **object**. In the former, the value cannot be split further into smaller R objects. Let us begin with two atomic types: `**numeric**`, and `**character**`.\n\n#### Numeric Variables\n\nThe simplest atomic type in R is the `numeric` data type. That includes whole numbers, decimal numbers, and numbers represented in scientific notation ($6.023\\times10^{23}$). In mathematics, an atomic variable is a **scalar**. Here are some examples:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Decimal\nheight <- 5.6\n\n# Whole number (Integer)\nsample_size <- 15\n\n# Scientific notation\navogadro_number <- 6.023e23\n```\n:::\n\n\nDon't be mistaken, the `e` in the scientific notation refers to base `10`, e.g., `6.023e23` is $6.023\\times10^{23}$.\n\n`<-` denotes the assignment operator. Upon execution, the resultant value of the expression on the right-hand side, if no error, is stored in the named variable on the left-hand side. In RStudio, you can see the variable name and its associated value under the **Environment** tab, which usually occupies the top right quadrant of the RStudio desktop.\n\nNote that R supports two equivalent assignment operators. You can use `<-` and `=` interchangeably. I prefer `<-` to `=` as `=` can easily confuse with the equality checking operator `==`.\n\n**Arithmetic Operators**\n\nArithmetic operators that can apply to numeric variables include `+`, `-`, `*`, `/`, `**`, and `^`. The last two operators - `**` and `^` - are exponential; they perform exactly the same function. Here are some examples:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nradius <- 2.5\ndiameter <- 2*pi*radius\narea <- pi*radius**2\nvolume <- (4/3)*pi*radius^3\n```\n:::\n\n\nNote that `pi` is $\\pi$, which is a built-in variable with the value 3.141593.\n\nE.g., the height of an object is 5.6 feet:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nheight <- 5.6\n```\n:::\n\n\n#### Character Variables\n\nBesides numeric values, R also support operations of non-numeric values, which is called `**character**`. To define a character value, embrace the string of characters with a pair of quotes, either a pair of single or double quotes. E.g.,\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncourse <- 'BIOL265'\n```\n:::\n\n\nTo figure out whether a variable's type is numeric, character, or something else, use the `class()` function,\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(course)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"character\"\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(height)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"numeric\"\n```\n\n\n:::\n:::\n\n\nObviously, it does not make sense to do math with character type. E.g.,\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnucleotides*4\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError:\n! object 'nucleotides' not found\n```\n\n\n:::\n:::\n\n\n#### Vectors {#vectors}\n\nOne commonly used object in R is **`vectors`**. It comprises different components that can be processed collectively as a whole, or individually. A vector can be viewed pictorially as a wagon train. E.g.,\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# A simple numeric vector for the days in each month\ndays_of_month <- c(31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31)\n```\n:::\n\n\n`days_of_month` is a `vector` object in R. **`c()`** is the function that **combines or collates** several objects, as its name suggests, into a vector object. Elements are indexed or numbered from 1 to the total number of elements in the vector. You can extract a particular element by specifying the index within a pair of square-brackets. E.g.,\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Days in February\nprint(days_of_month[2])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 28\n```\n\n\n:::\n:::\n\n\n`[2]` means the 2^nd^ element of a vector. We will discuss more about indexing below. \n\nHere is an example of a character vector:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnucleotides <- c('A','C','G','T')\n```\n:::\n\n\nNoteworthy that all elements held inside a vector must have the same data type (**homogeneous**). For instance, `days_of_month` contains all numeric values, and `nucleotides` contains all character values. If you try to combine objects of different data types into a vector, R will convert them to character type. In the example below, even the first and third values are entered as numeric, R coerces them into character type, the common denominator type, `\"1\"` and `\"0\"`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\na_vector <- c(1, \"success\", 0, \"fail\")\na_vector\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"1\"       \"success\" \"0\"       \"fail\"   \n```\n\n\n:::\n:::\n\n\nOne of the R features that makes arithmetic operations on vectors really convenient is **vectorization**. For instance, if you want to standardize the values of a sample such that the sample mean and sample variance after standardization become 0 and 1, respectively. The formula for standardization is $z_{i}=\\frac{(x_{i}-\\bar{x})}{s}$, where $\\bar{x}$ and $s$ are the sample mean and sample standard deviation, respectively. Here's an example\n\n\n::: {.cell}\n\n```{.r .cell-code}\nheights <- c(5.5, 6.0, 6.1, 5.7, 5.9, 5.6)\nx_bar <- mean(heights)\ns <- sd(heights)\nstd_heights <- (heights - x_bar)/s\nstd_heights\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1.2677314  0.8451543  1.2677314 -0.4225771  0.4225771 -0.8451543\n```\n\n\n:::\n:::\n\n\nThe convenience is that you don't have to specify how to subtract and divide each height individually. Instead, R recognizes the expression `(heights-x_bar)` is to subtract an atomic `x_bar` (scalar) from a vector `heights`. Under the vectorization mechanism, it will subtract `x_bar` from every height in the vector `heights`, similarly for the division by `s`. \n\n`vector` is only one of the many types of objects supported by R, data frame is another commonly used object types, which will be discussed later.\n\n### Factors/Categorical Variables {#factor-levels}\n\nIn R, a categorical variable in statistics is called a **factor**. A categorical variable is further classified into **nominal** or **ordinal**. A nominal variable has no intrinsic order. The `factor()` function is used to define a categorical variable. E.g., a sample of colors is stored in a vector, and you want to define it as a nominal categorical variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolors <- c(\"Red\",\"Blue\",\"Blue\",\"Red\",\"Green\",\"Green\",\"Blue\",\"Green\",\"Red\",\"Blue\")\ncolors <- factor(colors, levels=c('Red','Blue','Green'))\ncolors\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] Red   Blue  Blue  Red   Green Green Blue  Green Red   Blue \nLevels: Red Blue Green\n```\n\n\n:::\n:::\n\n\nCategorical variables with intrinsic order are called **ordinal** variables. E.g., the stages of hypertension.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npatients <- c(\"Stage 2\",\"Hyperintensive\",\"Stage 2\",\"Hyperintensive\",\"elevated\",\"Stage 2\",\"elevated\",\"Stage 1\")\npatients <- factor(patients,\n                   levels=c('normal','elevated','Stage 1','Stage 2','Hyperintensive'),\n                   ordered = TRUE)\npatients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] Stage 2        Hyperintensive Stage 2        Hyperintensive elevated      \n[6] Stage 2        elevated       Stage 1       \nLevels: normal < elevated < Stage 1 < Stage 2 < Hyperintensive\n```\n\n\n:::\n:::\n\n\nAs you can see above, the hypertension levels are ordered and connected by a less than sign (`<`). \n### Data frames\n\nBesides `vector`, another commonly used object is `data frame`. Almost. all the datasets we will use for analysis are in a data frame format. Simply speaking, a data frame is a **tabular** or spreadsheet-like object, like an Excel or Google Sheets. A data frame consists of rows and columns. Each row represents a sample. Each column represents a variable. Rows are expected to have equal length, i.e., the same number of columns. If not, R will either complain or pad the missing columns with a special value `NA` (not available). Let's take a look at an R's built-in data frame `iris`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Show the first five rows\nhead(iris)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Sepal.Length Sepal.Width Petal.Length Petal.Width Species\n1          5.1         3.5          1.4         0.2  setosa\n2          4.9         3.0          1.4         0.2  setosa\n3          4.7         3.2          1.3         0.2  setosa\n4          4.6         3.1          1.5         0.2  setosa\n5          5.0         3.6          1.4         0.2  setosa\n6          5.4         3.9          1.7         0.4  setosa\n```\n\n\n:::\n:::\n\n\nYou can peek into the bottom five rows by the `tail()` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntail(iris)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Sepal.Length Sepal.Width Petal.Length Petal.Width   Species\n145          6.7         3.3          5.7         2.5 virginica\n146          6.7         3.0          5.2         2.3 virginica\n147          6.3         2.5          5.0         1.9 virginica\n148          6.5         3.0          5.2         2.0 virginica\n149          6.2         3.4          5.4         2.3 virginica\n150          5.9         3.0          5.1         1.8 virginica\n```\n\n\n:::\n:::\n\n\nAs you can see above, the `iris` data frame consists of five variables (columns). Here are the R functions to show the shape of a data frame:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# the dimension (row x column) of a data frame.\ndim(iris)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 150   5\n```\n\n\n:::\n\n```{.r .cell-code}\n# Only the number of rows\nnrow(iris)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 150\n```\n\n\n:::\n\n```{.r .cell-code}\n# Only the number of columns\nncol(iris)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5\n```\n\n\n:::\n:::\n\n\nSo, we know that `iris` contains 150 rows (flowers) and five columns.\n\n#### Accessing Rows and Columns of a Data Frame\n\nEach element in a data frame can be referenced by row and column indexes like the X-Y Cartesian system. Rows are automatically indexed (numbered), where the 1st row is index 1, the 2nd row is index 2, and the index of the last row is the total number of rows, similarly for columns. But often time, columns are named, such as the columns of `iris`; `Sepal.Width`, `Sepal.Length`, etc., as shown in Figure (\\@ref(fig:Fig1-1)). The two equivalent indexing schemes can occur in parallel.^[Rows can be named as well. This is left as an exercise for the readers.]\n\nThe syntax of accessing individual elements is `<data frame name>[row, column]`.\nE.g., the cell at the 5^th^ row and 3^rd^ column of the iris is:\n\n\n::: {.cell}\n\n```{.r .cell-code}\niris[5,3]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.4\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Accessing rows and columns of a data frame.](images/Figure_1.1.png)\n:::\n:::\n\n\nIf the column index is ignored, all columns of the specified row(s) are returned as shown in Figure (\\@ref(fig:Fig1-1)). For example, show all columns of the 3^rd^ row by:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Specify the row number only and leave out the column index.\niris[3,]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Sepal.Length Sepal.Width Petal.Length Petal.Width Species\n3          4.7         3.2          1.3         0.2  setosa\n```\n\n\n:::\n:::\n\n\nSimilarly, if the row index is skipped, all rows of the specified column(s) are returned (\\@ref(fig:Fig1-1)). For example, \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Specify only the column index.\nhead(iris[,5])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] setosa setosa setosa setosa setosa setosa\nLevels: setosa versicolor virginica\n```\n\n\n:::\n:::\n\n\nR provides an alternative way to access a single column of a data frame. The syntax is `<data frame name>$<column name>`. The equivalence of `iris[,5]` is `iris$Species`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(iris$Species)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] setosa setosa setosa setosa setosa setosa\nLevels: setosa versicolor virginica\n```\n\n\n:::\n:::\n\n\nNote that the `$` method only works for a single column. We will discuss a way shortly how to access multiple columns in one R command.\n\nBesides the numeric column index, columns can be referenced by names as shown in Figure (\\@ref(fig:Fig1-1)). E.g., the `Petal.Length` of the 5^th^ row:\n\n\n::: {.cell}\n\n```{.r .cell-code}\niris[5,'Petal.Length']\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.4\n```\n\n\n:::\n:::\n\n\nTo access more than one column and row, pack the row indices and column names in vectors by the function `c(...)`, which **c**ombines or **c**ollates several items into a vector object. For example, show the `Petal.Length` and `Sepal.Length` of the 123^th^ and 96^th^ rows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\niris[c(123,96),c('Petal.Length','Sepal.Length')]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Petal.Length Sepal.Length\n123          6.7          7.7\n96           4.2          5.7\n```\n\n\n:::\n:::\n\n\nUsing row index and column names is the basic accessing method. R provides additional methods to select rows and columns by conditions. More of this topic will be discussed in **Chapter 2: Data Wrangling**.\n\n#### Create a Data Frame\n\n\n## Descriptive Statistics\n\n### Summary Functions\n\n`length()` shows the number elements in an object. We will use a sample of pumpkin's weights for illustration.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# A sample of pumpkins' weights\npumpkins <- c(6.85,6.56,6.23,7.55,4.45,10.14,3.52,6.62,3.76,7.62)\n```\n:::\n\n\nThe `length()` shows the number of weights defined in `pumpkins`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlength(pumpkins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10\n```\n\n\n:::\n:::\n\n\nTo be clear, `length()` counts the number of elements in an R object, such as a vector or a data frame. **If the object is atomic, the function will return 1.** For example, in the following example, `dna` is a character (atomic). The function will return 1, not the number of characters.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndna <- 'ACGTAGC'\nlength(dna)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n:::\n\n\nThe `range()` prints the minimum and maximum values - numeric and non-numeric - of an object.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrange(pumpkins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  3.52 10.14\n```\n\n\n:::\n:::\n\n\nIf you are interested in either the minimum or maximum, here are the corresponding functions:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# The lightness\nmin(pumpkins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.52\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# The heaviest\nmax(pumpkins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10.14\n```\n\n\n:::\n:::\n\n\n### Non-robust Statistics\n\nMean, variance, and standard deviation are non-robust statistics, as they are sensitive to outliers (extreme values).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# A sample of pumpkins' weights\npumpkins <- c(6.85,6.56,6.23,7.55,4.45,10.14,3.52,6.62,3.76,7.62)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# The average weight\nmean(pumpkins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6.33\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# The variance\nvar(pumpkins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.013489\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# the standard deviation\nsd(pumpkins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.003369\n```\n\n\n:::\n:::\n\n\n### Robust Statistics\n\nMedian and quantile are robust statistics, as outliers minimally influence their values.\n\n*Median*\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# A sample of pumpkins' weights\npumpkins <- c(6.85,6.56,6.23,7.55,4.45,10.14,3.52,6.62,3.76,7.62)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmedian(pumpkins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6.59\n```\n\n\n:::\n:::\n\n\n*Quantile*\n\nStandard quantile intervals.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(pumpkins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    0%    25%    50%    75%   100% \n 3.520  4.895  6.590  7.375 10.140 \n```\n\n\n:::\n:::\n\n\nA customized quantile intervals.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(pumpkins, probs = c(0.1,0.9))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  10%   90% \n3.736 7.872 \n```\n\n\n:::\n:::\n\n\nA specific quantile.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(pumpkins, probs = c(0.05))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   5% \n3.628 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(pumpkins, probs = c(0.95))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  95% \n9.006 \n```\n\n\n:::\n:::\n\n\n**Inter-quantile Region (IQR)**\n\n$$IQR = Q3 - Q1$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nIQR(pumpkins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.48\n```\n\n\n:::\n:::\n\n\n### `summary()` Function\n\nA data frame may consists of many variables of different types in various ranges. Therefore, it makes a lot of sense to take a glimpse of all variables before analysis. It can be done by the `summary()` function to reveal:\n\n1.  The variable type of each column.\n\n2.  If the column is numeric, a summary of numeric values.\n\n3.  If the column is categorical (factor), what are the levels and order, if it is ordinal.\n\nLet's see the summary of `iris`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(iris)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Sepal.Length    Sepal.Width     Petal.Length    Petal.Width   \n Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100  \n 1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300  \n Median :5.800   Median :3.000   Median :4.350   Median :1.300  \n Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199  \n 3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800  \n Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500  \n       Species  \n setosa    :50  \n versicolor:50  \n virginica :50  \n                \n                \n                \n```\n\n\n:::\n:::\n\n\nThe summary will show the range (min. and max.) and quantiles of a numeric column. For a categorical variable (factor), it will show the levels with the number of samples (rows) found for each level, e.g., `Species` is a nominal variable, with 50 samples per species.\n\n## Utilities\n\n### Printing and Formatting\n\nR provides a function called `print()` that prints text to the console. E.g.,\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(\"Hello World!\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Hello World!\"\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nradius <- 2.5\ndiameter <- 2*pi*radius\nprint(diameter)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 15.70796\n```\n\n\n:::\n:::\n\n\nSuppose you want to improve the printout by making it more readable, say `\"The diameter of a circle with radius 2.5 cm is 15.70796.\"` In such a case, you need the format function `paste()`. Here's how to use it:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nradius <- 2.5\ndiameter <- 2*pi*radius\nprint(paste(\"The diameter of a circle with radius\",radius,\"cm is\",diameter,\".\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"The diameter of a circle with radius 2.5 cm is 15.707963267949 .\"\n```\n\n\n:::\n:::\n\n\nThe above printout is almost perfect. If you're picky, you don't like the extra space separating the diameter and the period in the above message, you can use `paste()`'s cousin function `paste0()`. The difference between the two is that `paste0()` will not automatically add an extra space between each component given to the function. Below is the previous print statement with `paste0()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(paste0(\"The diameter of a circle with radius\",radius,\"cm is\",diameter,\".\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"The diameter of a circle with radius2.5cm is15.707963267949.\"\n```\n\n\n:::\n:::\n\n\nAs you can see, there is no more space between the diameter and the period. But it created other issues; there is no space between \"The diameter of a circle with radius\" and the actual radius as well. So, when you use `paste0()`, you have to take care of the space separation yourselves. Here is the final version for using `paste0()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(paste0(\"The diameter of a circle with radius \",radius,\" cm is \",diameter,\".\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"The diameter of a circle with radius 2.5 cm is 15.707963267949.\"\n```\n\n\n:::\n:::\n\n\n### `seq()` - create a series of numbers {#seq-function}\n\nThere are situations where we need a series of equal-interval numbers. For example, override the default breaks - x-ticks - of a histogram, a vector containing all possible outcomes of tossing two dice, i.e, from 2 to 12.\n\nIn R, the `seq()` function generates a list of equal-interval numbers, whole and decimal. `seq()` takes the following parameters:\n\n1.  `from = 1`, the default is 1.\n\n2.  `to = 1`, the default is 1.\n\n3.  `by = 1`, the size of the interval between two adjacent numbers. It takes integer and decimal numbers. If it is negative, the series is decreasing.\n\n4.  `length.out` specifies how many numbers are returned. This option is an alternative to `by` when you care only about how many numbers are generated instead of the interval between them. See the example below.\n\n5.  `along.with`, it generates the same number of numbers according to what is provided to the `along.with` parameter.\n\n**Examples**\n\nBy default, `seq()` begins with 1 and has an interval of 1. E.g., generate 10 integers starting with 1.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseq(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1]  1  2  3  4  5  6  7  8  9 10\n```\n\n\n:::\n:::\n\n\nStaring from and ending with.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseq(-10,10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] -10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7   8\n[20]   9  10\n```\n\n\n:::\n:::\n\n\nSpecify the interval.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseq(-10,10, by=2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] -10  -8  -6  -4  -2   0   2   4   6   8  10\n```\n\n\n:::\n:::\n\n\nA decreasing sequence.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseq(10,by=-1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 10  9  8  7  6  5  4  3  2  1\n```\n\n\n:::\n:::\n\n\nJust specify the desired numbers to be generated. As you can see, the interval is pretty precise.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseq(-5,7,length.out=20)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] -5.00000000 -4.36842105 -3.73684211 -3.10526316 -2.47368421 -1.84210526\n [7] -1.21052632 -0.57894737  0.05263158  0.68421053  1.31578947  1.94736842\n[13]  2.57894737  3.21052632  3.84210526  4.47368421  5.10526316  5.73684211\n[19]  6.36842105  7.00000000\n```\n\n\n:::\n:::\n\nGenerate a sequence that matches the same number in another sequence.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- seq(1,5)\ncat(\"x =\",x,\"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nx = 1 2 3 4 5 \n```\n\n\n:::\n\n```{.r .cell-code}\ny <- seq(-5, along.with=x)\ncat(\"y =\",y,\"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ny = -5 -4 -3 -2 -1 \n```\n\n\n:::\n:::\n\n\n**Note:** What is the difference between `cat(...)` and `print(paste(...))` you saw above? The main difference is that `print(paste(...))` creates an R object (a text) and then prints it, while `cat(...)` directly writes text to the console without creating a formal R object. See example below you will understand the nuance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmsg1 <- print(paste(\"Hello\",\"World\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Hello World\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(msg1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Hello World\"\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmsg2 <- cat(\"Hello\",\"World\",\"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHello World \n```\n\n\n:::\n\n```{.r .cell-code}\nprint(msg2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNULL\n```\n\n\n:::\n:::\n\n\nIs it really important? No, unless you're a R developer.\n\n### `with()`\n\nIt set up the context of a data frame so it spares you from using the `$` to access the columns of a data frame. It is commonly used together with a function applied to one or more columns. E.g., the median of `Petal.Width`. It can done in two ways:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Use $\nmedian(iris$Petal.Width)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.3\n```\n\n\n:::\n\n```{.r .cell-code}\n# Or, use with()\nwith(iris, median(Petal.Width))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.3\n```\n\n\n:::\n:::\n\n\nFor the straightforward example above, you do not see the value of `with()`. Let's consider a more complicated row selection example. Find `Sepal.Length` in `iris` where its `Petal.Length` is less than 4 and `Petal.Width` is greater than 1. The `$`-way is:\n\n\n::: {.cell}\n\n```{.r .cell-code}\niris$Sepal.Length[iris$Petal.Length<4 & iris$Petal.Width>1]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.2 5.6 5.6 5.5 5.8 5.1\n```\n\n\n:::\n:::\n\n\nHere's the `with()` version that saves typing `iris` repeatedly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwith(iris, Sepal.Length[Petal.Length<4 & Petal.Width>1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.2 5.6 5.6 5.5 5.8 5.1\n```\n\n\n:::\n:::\n\n\nIn short, `with()` is English, so it improves the readability of R statements. Second, it saves some typing of the data frame's name. I recommend using `with()` whenever possible.\n\n## Summary\n\nThat's a bare minimum of R scripting required for data analysis. In the next chapter, we will focus on operations applied to data frames. Before you leave, it is useful to recap the R functions discussed in this chapter:\n\n<!--\n`<-`, `c()`, `print()`, `paste()`, `paste0()`, `cat()`, `class()`, `factor()`, `head()`, `tail()`, `dim()`, `nrow()`, `ncol()`, `summary()`, `mean()`, `var()`, `sd()`, `range()`, `min()`, `max()`, `median()`, `quantile()`, `IQR()`, `seq()`, and `with()`.\n-->\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: A Summary of R Operators and Functions\n\n|           |            |             |         |\n|:----------|:-----------|:------------|:--------|\n|`<-`       |`head()`    |`sd()`       |`with()` |\n|`c()`      |`tail()`    |`range()`    |+        |\n|`print()`  |`dim()`     |`min()`      |-        |\n|`paste()`  |`nrow()`    |`max()`      |*        |\n|`paste0()` |`ncol()`    |`median()`   |/        |\n|`cat()`    |`summary()` |`quantile()` |**       |\n|`class()`  |`mean()`    |`IQR()`      |^        |\n|`factor()` |`var()`     |`seq()`      |==       |\n\n\n:::\n:::\n\n<!--\n## Exercises {-}\n\n**Q1. Identify illegal variable names.**\n\nA. `fiveguys` B. `5guys` C. `five.guys` D. `five-guys` E. `five_guys`\n\n\n::: {.cell}\n\n:::\n\n\n**Q2. **\n\n\n-->",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}