<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; Statistical Tests – A Little R Survival Kit</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05_Dive_Deeper.html" rel="next">
<link href="./03_Data_Visualization.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-d2a895b5cbb91adc99485585edf1e91f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04_Statistical_Tests.html">Part II</a></li><li class="breadcrumb-item"><a href="./04_Statistical_Tests.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Statistical Tests</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">A Little R Survival Kit</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part I</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_Part1_Basic_R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Basic R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_Data_Wrangling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Wrangling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_Data_Visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Visualization</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part II</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_Statistical_Tests.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Statistical Tests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_Dive_Deeper.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Dive Deeper</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives">Learning Objectives:</a></li>
  <li><a href="#housekeeping" id="toc-housekeeping" class="nav-link" data-scroll-target="#housekeeping"><span class="header-section-number">4.1</span> Housekeeping</a></li>
  <li><a href="#tests-for-quantitative-variables" id="toc-tests-for-quantitative-variables" class="nav-link" data-scroll-target="#tests-for-quantitative-variables"><span class="header-section-number">4.2</span> Tests for Quantitative Variables</a>
  <ul class="collapse">
  <li><a href="#one-sample-t-tests" id="toc-one-sample-t-tests" class="nav-link" data-scroll-target="#one-sample-t-tests"><span class="header-section-number">4.2.1</span> One-sample t-tests</a></li>
  <li><a href="#one-sided-t-tests" id="toc-one-sided-t-tests" class="nav-link" data-scroll-target="#one-sided-t-tests"><span class="header-section-number">4.2.2</span> One-sided t-tests</a></li>
  </ul></li>
  <li><a href="#two-sample-t-tests" id="toc-two-sample-t-tests" class="nav-link" data-scroll-target="#two-sample-t-tests"><span class="header-section-number">4.3</span> Two-sample t-tests</a>
  <ul class="collapse">
  <li><a href="#one-way-anova" id="toc-one-way-anova" class="nav-link" data-scroll-target="#one-way-anova"><span class="header-section-number">4.3.1</span> One-way ANOVA</a></li>
  <li><a href="#paired-t-tests" id="toc-paired-t-tests" class="nav-link" data-scroll-target="#paired-t-tests"><span class="header-section-number">4.3.2</span> Paired t-tests</a></li>
  </ul></li>
  <li><a href="#tests-for-categorical-variables" id="toc-tests-for-categorical-variables" class="nav-link" data-scroll-target="#tests-for-categorical-variables"><span class="header-section-number">4.4</span> Tests for Categorical Variables</a>
  <ul class="collapse">
  <li><a href="#one-categorical-variable" id="toc-one-categorical-variable" class="nav-link" data-scroll-target="#one-categorical-variable"><span class="header-section-number">4.4.1</span> One Categorical Variable</a></li>
  <li><a href="#two-categorical-variables" id="toc-two-categorical-variables" class="nav-link" data-scroll-target="#two-categorical-variables"><span class="header-section-number">4.4.2</span> Two Categorical Variables</a></li>
  </ul></li>
  <li><a href="#regression" id="toc-regression" class="nav-link" data-scroll-target="#regression"><span class="header-section-number">4.5</span> Regression</a>
  <ul class="collapse">
  <li><a href="#simple-linear-regression" id="toc-simple-linear-regression" class="nav-link" data-scroll-target="#simple-linear-regression"><span class="header-section-number">4.5.1</span> Simple Linear Regression</a></li>
  <li><a href="#multiple-linear-regression" id="toc-multiple-linear-regression" class="nav-link" data-scroll-target="#multiple-linear-regression"><span class="header-section-number">4.5.2</span> Multiple Linear Regression</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">4.6</span> Summary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04_Statistical_Tests.html">Part II</a></li><li class="breadcrumb-item"><a href="./04_Statistical_Tests.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Statistical Tests</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-04-statistical-tests" class="quarto-section-identifier"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Statistical Tests</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>R was inherently designed for statistical analysis. Therefore, it is justified to devote a chapter to statistical tests. Here, we will discuss a list of classic statistical tests with an emphasis on the Null Hypothesis Significance Test (NHST). We assume that readers have a sound background in undergraduate-level statistics, i.e., they know the t statistic, <span class="math inline">\(\chi^2\)</span> statistic, confidence interval, p-value, correlation, etc. The goal of this chapter, as well as the whole book, emphasizes using R - the how. For readers who need to refresh basic statistical concepts, there are many excellent introductory statistics textbooks freely available on the Internet<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> <a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> <a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>. Interested readers are recommended to consult them for further detail.</p>
<section id="learning-objectives" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="learning-objectives">Learning Objectives:</h2>
<ul>
<li><p>Test a quantitative variable in one, two, or more groups.</p></li>
<li><p>Test for one or two categorical variables.</p></li>
<li><p>Linear regression</p></li>
</ul>
</section>
<section id="housekeeping" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="housekeeping"><span class="header-section-number">4.1</span> Housekeeping</h2>
<p>We use two new data sets in this chapter: <code>FlightDelays</code>, and <code>Groceries</code> . Follow the steps below to import them into RStudio.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(resampledata)) {</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">'resampledata'</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: resampledata</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'resampledata'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:datasets':

    Titanic</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(resampledata)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"FlightDelays"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"Groceries"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Take a glimpse of the data sets.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(FlightDelays)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       ID       Carrier      FlightNo      Destination    DepartTime  
 Min.   :   1   AA:2906   Min.   :  71.0   BNA: 172    4-8am   : 699  
 1st Qu.:1008   UA:1123   1st Qu.: 371.0   DEN: 264    8-Noon  :1053  
 Median :2015             Median : 691.0   DFW: 918    Noon-4pm:1048  
 Mean   :2015             Mean   : 827.1   IAD:  55    4-8pm   : 972  
 3rd Qu.:3022             3rd Qu.: 787.0   MIA: 610    8-Mid   : 257  
 Max.   :4029             Max.   :2255.0   ORD:1785                   
                                           STL: 225                   
  Day       Month       FlightLength       Delay        Delayed30 
 Sun:551   May :1999   Min.   : 68.0   Min.   :-19.00   No :3432  
 Mon:630   June:2030   1st Qu.:155.0   1st Qu.: -6.00   Yes: 597  
 Tue:628               Median :163.0   Median : -3.00             
 Wed:564               Mean   :185.3   Mean   : 11.74             
 Thu:566               3rd Qu.:228.0   3rd Qu.:  5.00             
 Fri:637               Max.   :295.0   Max.   :693.00             
 Sat:453                                                          </code></pre>
</div>
</div>
<p>It contains 10 variables, out of which two are quantitative variables (<code>FlightLength</code>, and <code>Delay</code>), and the rest are categorical variables. Notice that there is a glitch: R mistakenly considered <code>FlightNo</code> as a quantitative variable. However, it does not affect us, as we do not use this variable here. If you want to convert it to a categorical variable (factor), here is the step:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>FlightDelays<span class="sc">$</span>FlightNo <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(FlightDelays<span class="sc">$</span>FlightNo)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The <code>Groceries</code> data set contains the product prices from Target and Walmart.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Groceries)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                               Product          Size   
 Annie's Macaroni &amp; Cheese                         : 1   Length   :30  
 Barilla Angel Hair Pasta                          : 1   N.unique :24  
 Betty Crocker Super Moist Chocolate Fudge Cake Mix: 1   N.blank  : 0  
 Campbell's Chicken Noodle Soup                    : 1   Min.nchar: 3  
 Cheez-it Original Baked                           : 1   Max.nchar: 8  
 Dinty Moore Hearty Meals Beef Stew                : 1                 
 (Other)                                           :24                 
     Target         Walmart            Units         UnitType 
 Min.   :0.990   Min.   :1.000   Length   :30   Length   :30  
 1st Qu.:1.827   1st Qu.:1.760   N.unique :16   N.unique : 3  
 Median :2.545   Median :2.340   N.blank  : 0   N.blank  : 0  
 Mean   :2.762   Mean   :2.706   Min.nchar: 1   Min.nchar: 2  
 3rd Qu.:3.140   3rd Qu.:2.955   Max.nchar: 2   Max.nchar: 5  
 Max.   :7.990   Max.   :6.980                                
                                                              </code></pre>
</div>
</div>
<p>Lastly, we need to activate <code>tidyverse</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressMessages</span>(<span class="fu">require</span>(tidyverse))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="tests-for-quantitative-variables" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="tests-for-quantitative-variables"><span class="header-section-number">4.2</span> Tests for Quantitative Variables</h2>
<section id="one-sample-t-tests" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="one-sample-t-tests"><span class="header-section-number">4.2.1</span> One-sample t-tests</h3>
<p>The goal of a one-sample t-test is to test if the mean of a quantitative variable is equal to a certain value. For example, if the aviation regulatory agency states that acceptable flight delay is 12 minutes. We want to see if the flights meet the requirement. The null hypothesis (<span class="math inline">\(H_{0}\)</span>) is that the mean delay is equal to 12 minutes. The alternative hypothesis (<span class="math inline">\(H_{A}\)</span>) is that the mean delay is not equal to 12 minutes. Here are the steps to perform such a test:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(FlightDelays<span class="sc">$</span>Delay, <span class="at">mu =</span> <span class="dv">12</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  FlightDelays$Delay
t = -0.39963, df = 4028, p-value = 0.6895
alternative hypothesis: true mean is not equal to 12
95 percent confidence interval:
 10.45205 13.02375
sample estimates:
mean of x 
  11.7379 </code></pre>
</div>
</div>
<p>As the p-value (0.6895) is greater than <span class="math inline">\(\alpha\)</span> = 0.05 at a 95% confidence level, we fail to reject the null hypothesis <span class="math inline">\(H_{0}\)</span>, meaning that the mean flight delay meets the standard.</p>
</section>
<section id="one-sided-t-tests" class="level3" data-number="4.2.2">
<h3 data-number="4.2.2" class="anchored" data-anchor-id="one-sided-t-tests"><span class="header-section-number">4.2.2</span> One-sided t-tests</h3>
<p>In the above flight delay example, the condition to reject the <span class="math inline">\(H_{0}\)</span> is that the delay time is either much longer or much shorter than 12 minutes (that is why the test is called two-sided). Indisputably, the latter case does not make much sense, as short delay times indicate the flights are punctual. Hence, the test must focus on long delay times by replacing the above two-sided test with a one-sided test in which the rejection region (<span class="math inline">\(H_{A}\)</span>) lies at larger t-statistics (on the right). The parameter <code>alternative="greater"</code> suggests a one-sided test where the rejection region lies at the greater value.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(FlightDelays<span class="sc">$</span>Delay, <span class="at">mu =</span> <span class="dv">12</span>, <span class="at">alternative =</span> <span class="st">"greater"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  FlightDelays$Delay
t = -0.39963, df = 4028, p-value = 0.6553
alternative hypothesis: true mean is greater than 12
95 percent confidence interval:
 10.65885      Inf
sample estimates:
mean of x 
  11.7379 </code></pre>
</div>
</div>
<p>The p-value 0.6553 is larger than <span class="math inline">\(\alpha\)</span> = 0.05, fail to reject the <span class="math inline">\(H_{0}\)</span> at a 95% significance level.</p>
</section>
</section>
<section id="two-sample-t-tests" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="two-sample-t-tests"><span class="header-section-number">4.3</span> Two-sample t-tests</h2>
<p>A two-sample t-test tests whether the mean of one group is the same as the other group. The <span class="math inline">\(H_{0}\)</span> states the two groups have the same mean, and the <span class="math inline">\(H_{A}\)</span> states otherwise.</p>
<p>For example, we want to compare the mean delays of the two carriers to determine whether they are the same.</p>
<p><em>Solution 1:</em></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>AA_delay <span class="ot">&lt;-</span> <span class="fu">subset</span>(FlightDelays, Carrier<span class="sc">==</span><span class="st">"AA"</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>UA_delay <span class="ot">&lt;-</span> <span class="fu">subset</span>(FlightDelays, Carrier<span class="sc">==</span><span class="st">"UA"</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(AA_delay<span class="sc">$</span>Delay, UA_delay<span class="sc">$</span>Delay)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  AA_delay$Delay and UA_delay$Delay
t = -3.8255, df = 1843.8, p-value = 0.0001349
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -8.903198 -2.868194
sample estimates:
mean of x mean of y 
 10.09738  15.98308 </code></pre>
</div>
</div>
<p>Based on the p-value (0.0001349) being less than <span class="math inline">\(\alpha\)</span> = 0.05, the delays of the two carriers are different. The bottom of the test results shows that the mean delay for AA (group x) is 10.09738, shorter than UA’s 15.98308.</p>
<p><em>Solution 2:</em></p>
<p>This approach makes use of the categorical variable <code>carrier</code> to split the data set into two, avoiding the creation of two temporary data frames.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Delay <span class="sc">~</span> Carrier, <span class="at">data=</span>FlightDelays)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  Delay by Carrier
t = -3.8255, df = 1843.8, p-value = 0.0001349
alternative hypothesis: true difference in means between group AA and group UA is not equal to 0
95 percent confidence interval:
 -8.903198 -2.868194
sample estimates:
mean in group AA mean in group UA 
        10.09738         15.98308 </code></pre>
</div>
</div>
<p>The symbol <code>~</code> means “split by”. <code>Delay ~ Carrier</code> means to split <code>Delay</code> by <code>Carrier</code>.</p>
<section id="one-way-anova" class="level3" data-number="4.3.1">
<h3 data-number="4.3.1" class="anchored" data-anchor-id="one-way-anova"><span class="header-section-number">4.3.1</span> One-way ANOVA</h3>
<p>A one-way ANOVA test tests whether the means of three or more groups are the same or not. Two key differences from the two-sample t-test above: 1. a two-sample t-test can handle only two groups, but ANOVA can handle two or more groups. 2. The <span class="math inline">\(H_{0}\)</span> of ANOVA is rejected if any pair(s) of groups have unequal means.</p>
<p>For example, test whether mean delays vary by destination.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>aov_results <span class="ot">&lt;-</span> <span class="fu">aov</span>(Delay <span class="sc">~</span> Destination, <span class="at">data=</span>FlightDelays)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(aov_results)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Df  Sum Sq Mean Sq F value   Pr(&gt;F)    
Destination    6   62891   10482   6.094 2.29e-06 ***
Residuals   4022 6918028    1720                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>If you only care whether the <span class="math inline">\(H_{0}\)</span> can be rejected, focus on the overall p-value (2.29e-06) under the <code>Pr(&gt;F)</code> column on the right. It is undeniably smaller than <span class="math inline">\(\alpha\)</span> = 0.05, so the <span class="math inline">\(H_{0}\)</span> can be rejected.</p>
<p>In some situations, you may be interested in finding out which pair(s) do not have the same mean. Tukey’s Honest Significant Difference (HSD) test can answer this question.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(aov_results)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = Delay ~ Destination, data = FlightDelays)

$Destination
               diff         lwr        upr     p adj
DEN-BNA   7.1454369  -4.8424432 19.1333171 0.5765602
DFW-BNA   3.2646932  -6.8999706 13.4293570 0.9647119
IAD-BNA  19.4461945   0.4951700 38.3972191 0.0399134
MIA-BNA  12.9137057   2.3518660 23.4755453 0.0058064
ORD-BNA   8.4338186  -1.3335463 18.2011835 0.1430105
STL-BNA   0.9181137 -11.4728506 13.3090780 0.9999910
DFW-DEN  -3.8807437 -12.4245377  4.6630503 0.8331281
IAD-DEN  12.3007576  -5.8325642 30.4340793 0.4140643
MIA-DEN   5.7682688  -3.2444158 14.7809533 0.4884472
ORD-DEN   1.2883817  -6.7786774  9.3554408 0.9991892
STL-DEN  -6.2273232 -17.3274143  4.8727678 0.6463375
IAD-DFW  16.1815013  -0.8016809 33.1646835 0.0736782
MIA-DFW   9.6490125   3.2584254 16.0395995 0.0001755
ORD-DFW   5.1691254   0.2003667 10.1378841 0.0352035
STL-DFW  -2.3465795 -11.4473015  6.7541425 0.9885164
MIA-IAD  -6.5324888 -23.7563253 10.6913477 0.9225580
ORD-IAD -11.0123759 -27.7607938  5.7360421 0.4540417
STL-IAD -18.5280808 -36.9303655 -0.1257961 0.0471723
ORD-MIA  -4.4798870 -10.2175372  1.2577631 0.2425378
STL-MIA -11.9955920 -21.5378772 -2.4533067 0.0039784
STL-ORD  -7.5157049 -16.1704244  1.1390145 0.1382159</code></pre>
</div>
</div>
<p>It lists all possible pairs of destinations. Since there are seven destinations, the total number of pairs is 21 (<code>choose(7,2)</code>).</p>
<p>Each row shows the difference of means (<code>diff</code>), the lower (<code>lwr</code>) and upper (<code>upr</code>) bounds of the confidence interval, and the adjusted p-value (<code>p adj</code>). Examining the p-value is the quickest way to identify pairs with unequal means. E.g., IAD-BNA in which the p-value is less than 0.05.</p>
<p>To ease analysis, it is suggested to plot the HSD result as below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>hsd_results <span class="ot">&lt;-</span> <span class="fu">TukeyHSD</span>(aov_results)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co"># las=1 causes the plot to print the pair name horizontally.</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(hsd_results, <span class="at">las=</span><span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_Statistical_Tests_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Confidence intervals not crossing zero (the vertical line) indicate pairs have unequal means.</p>
</section>
<section id="paired-t-tests" class="level3" data-number="4.3.2">
<h3 data-number="4.3.2" class="anchored" data-anchor-id="paired-t-tests"><span class="header-section-number">4.3.2</span> Paired t-tests</h3>
<p>A paired t-test detects whether two mean measurements of a sample differ. For example, in a drug trial, a subject’s blood pressure is measured before and after taking the tested drug. Each sample is a subject. The measurements are blood pressure. The <span class="math inline">\(H_{0}\)</span> is the mean difference between the two measurements from all samples is zero.</p>
<p>Here we will examine whether the product prices between Target and Walmart are different. The sample is a product. The two measurements are the prices from Target and Walmart.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(Groceries, <span class="fu">t.test</span>(Target, Walmart, <span class="at">paired=</span>T))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  Target and Walmart
t = 0.47046, df = 29, p-value = 0.6415
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 -0.1896825  0.3030159
sample estimates:
mean difference 
     0.05666667 </code></pre>
</div>
</div>
<p>The p-value of 0.6415 &gt; <span class="math inline">\(\alpha\)</span> = 0.05 suggests that there is no statistical difference between the two stores at the 95% confidence level. The mean price difference of all the products in the sample is 0.057, which is not considered a significant difference from zero.</p>
</section>
</section>
<section id="tests-for-categorical-variables" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="tests-for-categorical-variables"><span class="header-section-number">4.4</span> Tests for Categorical Variables</h2>
<section id="one-categorical-variable" class="level3" data-number="4.4.1">
<h3 data-number="4.4.1" class="anchored" data-anchor-id="one-categorical-variable"><span class="header-section-number">4.4.1</span> One Categorical Variable</h3>
<p>Here, we want to check whether the proportions of categories match a specified expected ratio. In standard textbooks, this test is called the Chi-square (<span class="math inline">\(\chi^{2}\)</span>) goodness-of-fit test. For example, <code>Delayed30</code> indicates whether the flight was delayed by more than 30 minutes; it is either Yes or No.&nbsp;Suppose the regulatory standard recommends not more than 10% of a random sample of flights. First, figure out how many Yes and No in the sample.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(FlightDelays<span class="sc">$</span>Delayed30)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  No  Yes 
3432  597 </code></pre>
</div>
</div>
<p>The data set contains 4,029 flights; 3,432 were punctual, and 587 were delayed. According to the standard, the number of delayed flights should be no more than 10% of the total, or 402. Due to random variation in sampling, we cannot conclude an issue is present simply because 587 is greater than 402. Here’s where the <span class="math inline">\(\chi^2\)</span>-test comes in.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">table</span>(FlightDelays<span class="sc">$</span>Delayed30), <span class="at">p=</span><span class="fu">c</span>(<span class="fl">0.9</span>,<span class="fl">0.1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Chi-squared test for given probabilities

data:  table(FlightDelays$Delayed30)
X-squared = 103.9, df = 1, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The <span class="math inline">\(H_{0}\)</span> assumes the proportions agree with the expected ratio. The p-value shown above is literally zero, indicating that the proportions of Yes and No do not conform to the expected 9:1 ratio at the 95% confidence level.</p>
<p>One remark about setting up the proportion parameter <code>p=c(0.9,0.1)</code>. Make sure that the order of the proportions matches the sequence of the categories produced by the <code>table()</code> function. Additionally, the proportions must sum to 1.</p>
</section>
<section id="two-categorical-variables" class="level3" data-number="4.4.2">
<h3 data-number="4.4.2" class="anchored" data-anchor-id="two-categorical-variables"><span class="header-section-number">4.4.2</span> Two Categorical Variables</h3>
<p>Here we examine the dependency between two categorical variables. The test is colloquially called <span class="math inline">\(\chi^{2}\)</span> Test for Independence. For example, we want to know whether a delay of more than 30 minutes depends on the carrier, that is to say whether <code>Delayed30</code> is independent of <code>Carrier</code>. The <span class="math inline">\(H_{0}\)</span> assumes that they are independent.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(FlightDelays, <span class="fu">chisq.test</span>(Carrier, Delayed30, <span class="at">correct=</span><span class="cn">TRUE</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  Carrier and Delayed30
X-squared = 13.462, df = 1, p-value = 0.0002434</code></pre>
</div>
</div>
<p>Note that <code>correct=TRUE</code> instructs the test function to make adjustments in calculating the <span class="math inline">\(\chi^2\)</span> statistic. The correction is only applicable for a 2x2 contingency table with small counts. However, it does little harm if you turn it on for tables with a different dimension or large counts<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>. My suggestion is to turn it on all the time.</p>
<p>As the p-value of 0.0002434 is less than 0.05, reject the <span class="math inline">\(H_{0}\)</span> at the 95% confidence level, meaning that <code>Delay30</code> and <code>Carrier</code> are not independent. This conclusion suggests that the proportion of delayed flights differs between the two carriers. To be clear, their dependency says nothing about the carriers’ delay issue. To figure that out exactly, we should examine the proportion of delayed flights for each carrier using a new function <code>prop.table()</code> as below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(FlightDelays, <span class="fu">prop.table</span>(<span class="fu">table</span>(Carrier, Delayed30), <span class="at">margin=</span><span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Delayed30
Carrier        No       Yes
     AA 0.8647626 0.1352374
     UA 0.8183437 0.1816563</code></pre>
</div>
</div>
<p>We feed the contingency table of <code>Carrier</code> by <code>Delayed30</code> to the <code>prop.table()</code> function with <code>margin=1</code>, meaning that values are divided by the row totals or the sum of the proportions for each row is 1. As you can see, both carriers have an issue under the 10% rule, but the issue with UA is more severe than AA.</p>
</section>
</section>
<section id="regression" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="regression"><span class="header-section-number">4.5</span> Regression</h2>
<section id="simple-linear-regression" class="level3" data-number="4.5.1">
<h3 data-number="4.5.1" class="anchored" data-anchor-id="simple-linear-regression"><span class="header-section-number">4.5.1</span> Simple Linear Regression</h3>
<p>A simple linear regression (SLR) model involves a predictor X (independent variable) and a response Y (dependent variable), where both of them are quantitative, but they have different roles.</p>
<p><span class="math display">\[Y = \beta_{0} + \beta_{1}X\]</span></p>
<p>where <span class="math inline">\(\beta_{0}\)</span> is the intercept, and <span class="math inline">\(\beta_{1}\)</span> is the slope.</p>
<p>The relationship between them in an SLR is linear and directional. Firstly, the predictor is believed to influence the response, and not the reverse; therefore, it is directional. For example, temperature (predictor) is supposed to influence ice cream sales (response), and not the other way.</p>
<p>Secondly, the relationship is linear, meaning that a unit increment of X will cause Y to increase or decrease by <span class="math inline">\(\beta_{1}\)</span> units for every X within the range of X in the data.</p>
<p>Finally, an SLR can only establish a correlation between X and Y, but not causation.</p>
<p>Here we will switch to the familiar built-in <code>iris</code> data set to demonstrate how to build an SLR. Suppose we are interested in whether <code>Sep.Length</code> (predictor) affects <code>Sep.Width</code> (response) for <code>setosa</code> species. The first step for building an SLR is to visualize the relationship between the two variables using a scatter plot (<a href="03_Data_Visualization.html#sec-baseR-scatter-plot" class="quarto-xref"><span>Section 3.2.5</span></a> or <a href="03_Data_Visualization.html#sec-ggplot-scatter-plot" class="quarto-xref"><span>Section 3.3.6</span></a>). Do not downplay the intuition of visual inspection. In the absence of an upward or downward trend, the attempt to build an SLR is deemed fruitless. On a positive note, the plot may still reveal an intriguing trend not as expected, requiring a different kind of model or variable transformation. Anyway, let’s plot the two variables.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>setosa_iris <span class="ot">&lt;-</span> <span class="fu">subset</span>(iris, Species<span class="sc">==</span><span class="st">'setosa'</span>)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>setosa_iris, <span class="fu">aes</span>(<span class="at">x=</span>Sepal.Length, <span class="at">y=</span>Sepal.Width)) <span class="sc">+</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_Statistical_Tests_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>As shown above, there is an upward trend even though it is not definitive for everyone. Subjectively, we will proceed to build an SLR model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>slr_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sepal.Width <span class="sc">~</span> Sepal.Length, <span class="at">data=</span>setosa_iris)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(slr_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Sepal.Width ~ Sepal.Length, data = setosa_iris)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.72394 -0.18273 -0.00306  0.15738  0.51709 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   -0.5694     0.5217  -1.091    0.281    
Sepal.Length   0.7985     0.1040   7.681 6.71e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2565 on 48 degrees of freedom
Multiple R-squared:  0.5514,    Adjusted R-squared:  0.542 
F-statistic: 58.99 on 1 and 48 DF,  p-value: 6.71e-10</code></pre>
</div>
</div>
<p>The slope and the intercept can be found under the <code>Estimate</code> column of <code>Coefficients</code> subsection. In this example, the intercept <span class="math inline">\(\beta_{0}\)</span> is -0.5694, and the slope <span class="math inline">\(\beta_{1}\)</span> (<code>Sepal.Length</code>) is 0.7985. So the SLR model is:</p>
<p><span class="math display">\[Sepal.Width = -0.5694 + 0.7985 \times Sepal.Length   \]</span></p>
<p>The SLR model says that a unit increase in <code>Sepal.Length</code>, <code>Sepal.Width</code> will increase by 0.7985 units.</p>
<p>To judge whether they are statistically significant, examine the p-values under the column <code>Pr(&gt;|t|)</code>. The p-value of the slope is close to zero, suggesting that it is statistically significant; unfortunately, the intercept is not. It means that the linear correlation between <code>Sepal.Width</code> and <code>Sepal.Length</code> is strong. However, it is completely accurate to predict <code>Sepal.Width</code> using <code>Sepal.Length</code>.</p>
<p>Since we mentioned correlation, the <code>Multiple R-squared</code> is the square of Pearson’s correlation between the two variables. Let’s verify this.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Pearson's correlation</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fu">with</span>(setosa_iris, <span class="fu">cor</span>(Sepal.Length, Sepal.Width))</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Pearson's correlation ="</span>,r))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Pearson's correlation = 0.74254668566516"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Square of Pearson's correlation is Multiple R-squared</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"The square of r ="</span>,r<span class="sc">**</span><span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "The square of r = 0.551375580392314"</code></pre>
</div>
</div>
</section>
<section id="multiple-linear-regression" class="level3" data-number="4.5.2">
<h3 data-number="4.5.2" class="anchored" data-anchor-id="multiple-linear-regression"><span class="header-section-number">4.5.2</span> Multiple Linear Regression</h3>
<p>A multiple linear regression (MLR) model involves one response and two or more predictors. The equation for MLR is</p>
<p><span class="math display">\[Y = \beta_{0} + \beta_{1} \times X_{1} + ... + \beta_{n} \times X_{n}\]</span></p>
<p>Suppose we are keen to predict <code>Sepal.Width</code> by <code>Sepal.Length</code> and <code>Petal.Length</code> for setosa iris. Similar to SLR, we visualize the data but using a multipanel scatter plot <a href="03_Data_Visualization.html#sec-baseR-multipanel-scatter-plot" class="quarto-xref"><span>Section 3.2.6</span></a>, <a href="03_Data_Visualization.html#sec-ggplot-multipanel-scatter-plot" class="quarto-xref"><span>Section 3.3.7</span></a>).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(setosa_iris[,<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>], <span class="at">main=</span><span class="st">"A Multi-Panel Scatter Plot"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_Statistical_Tests_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Here we visualize the trend between <code>Sepal.Width</code> and <code>Sepal.Length</code> (2<sup>nd</sup> row and 1<sup>st</sup> column), and <code>Sepal.Width</code> and <code>Petal.Length</code> (2<sup>nd</sup> row and 3<sup>rd</sup> column). Despite the trend not being clear between <code>Sepal.Width</code> and <code>Petal.Length</code> , let’s proceed to build an MLR model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>mlr_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sepal.Width <span class="sc">~</span> Sepal.Length <span class="sc">+</span> Petal.Length, <span class="at">data=</span>setosa_iris)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mlr_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Sepal.Width ~ Sepal.Length + Petal.Length, data = setosa_iris)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.72858 -0.18414 -0.00301  0.16460  0.51769 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -0.53038    0.55609  -0.954    0.345    
Sepal.Length  0.80493    0.10897   7.387 2.13e-09 ***
Petal.Length -0.04863    0.22118  -0.220    0.827    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2591 on 47 degrees of freedom
Multiple R-squared:  0.5518,    Adjusted R-squared:  0.5328 
F-statistic: 28.94 on 2 and 47 DF,  p-value: 6.438e-09</code></pre>
</div>
</div>
<p>Based on the p-values, only <code>Sepal.Length</code> is a stable predictor of <code>Sepal.Width</code>.</p>
</section>
</section>
<section id="summary" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="summary"><span class="header-section-number">4.6</span> Summary</h2>
<p>In this chapter, we have discussed classical statistical tests that …</p>
<p>Put a table of tests here.</p>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Introductory Statistics for Life and Biomedical Sciences: <a href="https://openintro.org/book/biostat/" class="uri">https://openintro.org/book/biostat/</a><a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Introduction to Modern Statistics: <a href="https://openintro.org/book/ims/" class="uri">https://openintro.org/book/ims/</a><a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Handbook of Biological Statistics: <a href="https://www.biostathandbook.com/" class="uri">https://www.biostathandbook.com/</a><a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p><a href="https://en.wikipedia.org/wiki/Yates%27s_correction_for_continuity" class="uri">https://en.wikipedia.org/wiki/Yates%27s_correction_for_continuity</a><a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./03_Data_Visualization.html" class="pagination-link" aria-label="Data Visualization">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Visualization</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./05_Dive_Deeper.html" class="pagination-link" aria-label="Dive Deeper">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Dive Deeper</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>